### ISSUE TITLE
Prop protection replacement

### ISSUE THREAD

**Issue by GamerXsakuboy99** [GamerXsakuboy99/Metrostroi-Europe-server#5]
Replacing Prop Protect with something else.

**Comment by GamerXsakuboy99** [comment]
Replaced PatchProcted to Falco prop protection.

Needs bit work before server is opened to public.

**Comment by Spykiller45** [comment]
oh nice change

**Comment by GamerXsakuboy99** [comment]
replaced now, and server is open
